Repository AlgebraicJulia/AlgebraicPetri.jl, pull requests merged in 2020-07, with the labels that each got.

#2 Documentation
  .github/workflows/docs.yml
  README.md
  docs/Project.toml
  docs/make.jl
  docs/src/api.md
  docs/src/examples/covid.html
  docs/src/examples/epidemiology.html
  docs/src/index.md
  docs/src/usage.md
  examples/covid/covid.jl
  examples/covid/epidemiology.jl
  src/AlgebraicPetri.jl
Labels: documentation

#3 Simplified PetriCospan constructor
  .github/workflows/docs.yml
  Project.toml
  docs/Project.toml
  docs/make.jl
  docs/src/examples/covid.html
  docs/src/examples/epidemiology.html
  docs/src/index.md
  docs/src/usage.md
  examples/covid/covid.jl
  examples/covid/epidemiology.jl
  src/AlgebraicPetri.jl
  test/petri.jl
Labels: documentation, enhancement

#5 Global Epidemiology Presentation
  .github/workflows/docs.yml
  docs/make.jl
  examples/covid/covid.jl
  examples/covid/epidemiology.jl
  examples/predation/Project.toml
  examples/predation/lotka-volterra.jl
  src/AlgebraicPetri.jl
  src/Epidemiology.jl
Labels: enhancement

#6 Added some basic analytics
  docs/make.jl
  docs/src/assets/analytics.js
Labels: documentation

#10 Updated to Petriv1 with stochastic differential equations
  .gitignore
  Project.toml
  docs/Project.toml
  examples/covid/Project.toml
  examples/covid/_generate_figs.jl
  examples/covid/covid.jl
  examples/covid/epidemiology.jl
  examples/predation/lotka-volterra.jl
  src/AlgebraicPetri.jl
Labels: enhancement

#11 Fixed compat entries so packages are upgradable
  Project.toml
Labels: bug

#12 [WIP] implementation of whole-grained Petri nets
  src/Types.jl
Labels: enhancement
